# Generated by Django 3.2.5 on 2022-07-08 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
