# Generated by Django 3.2.5 on 2022-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='pfp/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
