# Generated by Django 3.2.5 on 2022-07-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_date_updated'),
        ('auction', '0002_auto_20220629_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='core.profile'),
        ),
        migrations.AddField(
            model_name='auction',
            name='initial_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='limit',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='meme',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='meme',
            name='file',
            field=models.FileField(editable=False, unique=True, upload_to='memes'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memes', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
