# Generated by Django 3.2.5 on 2022-07-08 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20220708_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
