# Generated by Django 3.2.5 on 2022-07-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_profile_picture'),
        ('auction', '0004_alter_meme_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='participants',
            field=models.ManyToManyField(related_name='auctions_participated', through='auction.Bid', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='bid',
            name='highest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_authored', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='file',
            field=models.FileField(editable=False, unique=True, upload_to='uploads/'),
        ),
    ]
