# Generated by Django 3.2.5 on 2022-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_bid_highest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
