# Generated by Django 3.2.5 on 2022-07-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_meme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ends_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starts_at',
            field=models.DateTimeField(null=True),
        ),
    ]
