# Generated by Django 3.2.5 on 2022-07-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20220721_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
